### ISSUE TITLE
LayoutXLM for Token Classification on FUNSD

### ISSUE THREAD

**Issue by TahaDouaji** [NielsRogge/Transformers-Tutorials#35] opened 2021-09-25 20:22 UTC
Hello Niels, first thanks a lot for all of your awesome tutorials, 
I'm trying to apply LayoutLM v2 Token classification [tutorial](https://github.com/NielsRogge/Transformers-Tutorials/blob/master/LayoutLMv2/FUNSD/Fine_tuning_LayoutLMv2ForTokenClassification_on_FUNSD.ipynb) on LayoutXLM, and I'm facing few issues.
I'm trying to have a processer for LayoutXLM, so converting this line
```
from transformers import LayoutLMv2Processor
processor = LayoutLMv2Processor.from_pretrained("microsoft/layoutlmv2-base-uncased", revision="no_ocr")
```
to those, but none worked.

```processor = LayoutLMv2Processor.from_pretrained("microsoft/layoutxlm-base", revision="no_ocr")```

```
feature_extractor = LayoutLMv2FeatureExtractor(apply_ocr=False)
tokenizer = LayoutLMv2TokenizerFast.from_pretrained("microsoft/layoutxlm-base")
processor = LayoutLMv2Processor(feature_extractor, tokenizer)
```
So, Can you please help me figure out what to change to have it work?
Many thanks in advance!.

**Comment by ManuelFay** [comment] 2021-09-27 13:34
You don't need to change the processor, just the model weights. Just keep the processor as is with the lmv2 and change the model path.

https://huggingface.co/transformers/model_doc/layoutxlm.html

**Comment by NielsRogge** [comment] 2021-09-27 13:36
Yes, but LayoutXLM also requires another tokenizer (based on XLM-RoBERTa).

I've updated the docs: https://huggingface.co/transformers/master/model_doc/layoutxlm.html

**Comment by ManuelFay** [comment] 2021-09-27 14:17
Using autotokenizer to load the xlmroberta tokenizer does not work, since it raises a ValueError when initializing the processor:
```python
def __init__(self, feature_extractor, tokenizer):
        if not isinstance(feature_extractor, LayoutLMv2FeatureExtractor):
            raise ValueError(
                f"`feature_extractor` has to be of type {LayoutLMv2FeatureExtractor.__class__}, but is {type(feature_extractor)}"
            )
        if not isinstance(tokenizer, (LayoutLMv2Tokenizer, LayoutLMv2TokenizerFast)):
            raise ValueError(
                f"`tokenizer` has to be of type {LayoutLMv2Tokenizer.__class__} or {LayoutLMv2TokenizerFast.__class__}, but is {type(tokenizer)}"
            )


        self.feature_extractor = feature_extractor
        self.tokenizer = tokenizer
...
```

Temporal fix for now is to load the tokenizer as:
```tokenizer = LayoutLMv2TokenizerFast.from_pretrained('microsoft/layoutxlm-base')```

**Comment by TahaDouaji** [comment] 2021-09-27 14:57
Thank you both @ManuelFay @NielsRogge for your replies!
Yes as mentioned above, the AutoTokenizer is not working, so how can we load the Tokenizer into our processor?

**Comment by ReyzGS** [comment] 2021-10-01 09:42
Hi, I'm having the same issue as @ManuelFay when using processor with AutoTokenizer. Did you find any fix for this?

**Comment by NielsRogge** [comment] 2021-10-01 09:45
Hi,

So the processor combines a feature extractor (for the image part) and a tokenizer (for the text part). LayoutLMv2 and LayoutXLM share the same feature extractor, but require a different tokenizer. The problem is that currently, the tokenizer for LayoutXLM does not support bounding boxes. You should use the XLMRobertaTokenizer, like so:

```
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("microsoftlayoutxlm-base")
```

So for now, one cannot use the processor for LayoutXLM. One should instead use the feature extractor and tokenizer separately to prepare the data for the model.

**Comment by ReyzGS** [comment] 2021-10-01 10:28
Thank you so much for your quick reply! I will try that!

**Comment by NielsRogge** [comment] 2021-11-03 08:01
Good news, `LayoutXLMProcessor` is now available (the PR linked above has been merged)!

You should install Transformers from source for now to use it: `pip install git+https://github.com/huggingface/transformers.git`.

Therefore, closing this issue.

**Closed by NielsRogge** 2021-11-03 08:01 UTC
